import { Router } from "express";
import { authMiddleware } from "../../middlewares/auth.middleware";
import { LobbiesController } from "./lobbies.controller";
const lobbiesRoutes = Router({ mergeParams: true });
const lobbiesController = new LobbiesController();
lobbiesRoutes.get("/", authMiddleware, lobbiesController.list.bind(lobbiesController));
lobbiesRoutes.get("/:lobbyId", authMiddleware, lobbiesController.show.bind(lobbiesController));
lobbiesRoutes.post("/", authMiddleware, lobbiesController.create.bind(lobbiesController));
lobbiesRoutes.post("/:lobbyId/join", authMiddleware, lobbiesController.join.bind(lobbiesController));
lobbiesRoutes.post("/:lobbyId/start", authMiddleware, lobbiesController.start.bind(lobbiesController));
lobbiesRoutes.post("/:lobbyId/team-selection/vote", authMiddleware, lobbiesController.voteTeamSelection.bind(lobbiesController));
lobbiesRoutes.post("/:lobbyId/team-selection/confirm", authMiddleware, lobbiesController.confirmTeamSelection.bind(lobbiesController));
lobbiesRoutes.post("/:lobbyId/team-selection/captain-vote", authMiddleware, lobbiesController.voteCaptain.bind(lobbiesController));
lobbiesRoutes.post("/:lobbyId/team-selection/captains/finalize", authMiddleware, lobbiesController.finalizeCaptains.bind(lobbiesController));
lobbiesRoutes.post("/:lobbyId/team-selection/pick", authMiddleware, lobbiesController.draftPick.bind(lobbiesController));
lobbiesRoutes.patch("/:lobbyId/ready", authMiddleware, lobbiesController.ready.bind(lobbiesController));
lobbiesRoutes.patch("/:lobbyId/unready", authMiddleware, lobbiesController.unready.bind(lobbiesController));
lobbiesRoutes.patch("/:lobbyId/team", authMiddleware, lobbiesController.changeTeam.bind(lobbiesController));
lobbiesRoutes.delete("/:lobbyId", authMiddleware, lobbiesController.cancel.bind(lobbiesController));
lobbiesRoutes.post("/:lobbyId/cancel", authMiddleware, lobbiesController.cancel.bind(lobbiesController));
lobbiesRoutes.delete("/:lobbyId/leave", authMiddleware, lobbiesController.leave.bind(lobbiesController));
export { lobbiesRoutes };
