import { ArrowRight, Plus, Sparkles, Trophy, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { CreateLeagueDialog } from "@/modules/leagues/components/CreateLeagueDialog";
import { useMineLeagues } from "@/modules/leagues/hooks/useMineLeagues";
export function DashboardPage() {
    const leagues = useMineLeagues();
    const items = leagues.data ?? [];
    const totalMembers = items.reduce((sum, league) => sum + Number(league.playerCount || 0), 0);
    return <div className="space-y-8">
    <section className="relative overflow-hidden rounded-3xl bg-primary p-6 text-primary-foreground shadow-lg shadow-primary/15 sm:p-9"><div className="absolute -right-12 -top-20 h-56 w-56 rounded-full bg-white/10"/><div className="relative flex flex-col gap-7 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="flex items-center gap-2 text-sm font-medium text-white/75"><Sparkles className="h-4 w-4"/> Central de competição</p><h1 className="mt-3 text-3xl font-bold text-white sm:text-4xl">Pronto para a próxima partida?</h1><p className="mt-3 text-white/70">Acesse uma liga existente ou crie uma nova comunidade para começar.</p></div><div className="flex flex-col gap-2 sm:flex-row"><CreateLeagueDialog /><Button variant="secondary" asChild><Link to="/leagues">Explorar ligas <ArrowRight className="h-4 w-4"/></Link></Button></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Trophy className="h-5 w-5"/></span><span className="text-3xl font-bold">{leagues.isLoading ? "—" : items.length}</span></div><p className="mt-4 font-medium">Minhas ligas</p><p className="text-sm text-muted-foreground">Competições das quais você participa.</p></article><article className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-700"><Users className="h-5 w-5"/></span><span className="text-3xl font-bold">{leagues.isLoading ? "—" : totalMembers}</span></div><p className="mt-4 font-medium">Jogadores conectados</p><p className="text-sm text-muted-foreground">Total de membros nas suas ligas.</p></article></section>
    <section className="space-y-4"><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Acesso rápido</h2><p className="text-sm text-muted-foreground">Continue de onde parou.</p></div><Button variant="ghost" asChild><Link to="/leagues">Ver todas <ArrowRight className="h-4 w-4"/></Link></Button></div>{leagues.isError ? <div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-6 text-destructive">Não foi possível carregar suas ligas.</div> : items.length ? <div className="grid gap-4 md:grid-cols-2">{items.slice(0, 4).map(league => <Link key={league.id} to={`/leagues/${league.id}`} className="group rounded-2xl border bg-card p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold group-hover:text-primary">{league.name}</h3><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{league.description || "Sem descrição."}</p></div><ArrowRight className="h-4 w-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-1"/></div><p className="mt-4 flex items-center gap-1.5 text-xs text-muted-foreground"><Users className="h-3.5 w-3.5"/>{league.playerCount}/{league.maxPlayers} membros</p></Link>)}</div> : !leagues.isLoading && <div className="rounded-2xl border border-dashed bg-card p-10 text-center"><Plus className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 font-medium">Você ainda não participa de uma liga.</p><p className="mt-1 text-sm text-muted-foreground">Crie a primeira ou encontre uma comunidade.</p></div>}</section>
  </div>;
}
