import { Router } from "express";
import { authMiddleware } from "../../middlewares/auth.middleware";
import { MatchesController } from "./matches.controller";
const controller = new MatchesController();
export const matchesRoutes = Router();
matchesRoutes.get("/:matchId", authMiddleware, controller.show.bind(controller));
matchesRoutes.post("/:matchId/votes", authMiddleware, controller.vote.bind(controller));
matchesRoutes.post("/:matchId/resolve", authMiddleware, controller.resolve.bind(controller));
export const leagueMatchesRoutes = Router({ mergeParams: true });
leagueMatchesRoutes.get("/", authMiddleware, controller.list.bind(controller));
leagueMatchesRoutes.get("/standings", authMiddleware, controller.standings.bind(controller));
